(()=>{if(window.__ccErrorMonitorInstalled)return;window.__ccErrorMonitorInstalled=true;
const URL="https://rwfamxkfqslorxcryjrp.supabase.co",KEY="sb_publishable_tzfe2xVn6OAwF-Mh5_u_zQ_a_bAW7tO",VERSION="3.7.14";
const read=()=>{try{const q=JSON.parse(localStorage.getItem("cc_error_queue")||"[]");return Array.isArray(q)?q:[]}catch{return[]}};
const write=q=>{try{localStorage.setItem("cc_error_queue",JSON.stringify(q.slice(-50)))}catch{}};
const recent=new Map();
const payloadFor=(err,meta={})=>{const e=err instanceof Error?err:new Error(String(err||"Unknown error"));return{p_app_name:"CleanCore Website",p_app_version:VERSION,p_page:location.pathname.split("/").pop()||"index.html",p_url:location.href,p_action:meta.action||"website_error",p_error_name:e.name||"Error",p_message:String(e.message||e).slice(0,4000),p_stack:String(e.stack||"").slice(0,12000),p_context:{...(meta.context||{}),source:"customer_website_global_monitor"},p_user_agent:navigator.userAgent}};
const send=async p=>{try{const r=await fetch(URL+"/rest/v1/rpc/log_client_error",{method:"POST",headers:{"apikey":KEY,"Authorization":"Bearer "+KEY,"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(p),keepalive:true});if(!r.ok)throw new Error("Error logger HTTP "+r.status);return true}catch{return false}};
const flush=async()=>{const q=read(),keep=[];for(const p of q){if(!(await send(p)))keep.push(p)}write(keep)};
const report=(err,meta={})=>{const p=payloadFor(err,meta),key=p.p_page+"|"+p.p_action+"|"+p.p_error_name+"|"+p.p_message;if(recent.has(key))return;recent.set(key,Date.now());setTimeout(()=>recent.delete(key),5000);void send(p).then(ok=>{if(!ok){const q=read();q.push(p);write(q)}})};
window.addEventListener("error",e=>report(e.error||new Error(e.message||"Unhandled browser error"),{action:"window_error",context:{source:e.filename||"",line:e.lineno||0,column:e.colno||0}}),true);
window.addEventListener("unhandledrejection",e=>report(e.reason||new Error("Unhandled promise rejection"),{action:"unhandled_rejection"}));
document.addEventListener("error",e=>{const t=e.target;if(t&&(t.tagName==="IMG"||t.tagName==="SCRIPT"||t.tagName==="LINK"))report(new Error("Failed to load "+t.tagName.toLowerCase()+": "+(t.src||t.href||"")),{action:"resource_load_error",context:{resource:t.src||t.href||"",tag:t.tagName}})},true);
const originalConsoleError=console.error.bind(console);console.error=(...args)=>{try{const msg=args.map(x=>typeof x==="string"?x:(x?.message||JSON.stringify(x))).join(" ").slice(0,4000);report(new Error(msg||"Console error"),{action:"console_error",context:{console_arguments:msg}})}catch{}originalConsoleError(...args)};
window.addEventListener("online",()=>void flush());
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>void flush());else void flush();
window.reportCustomerWebsiteError=(err,meta={})=>report(err,meta);
})();